name: CI

on:
  push:
    paths: &code
      - "src/**"
      - "ui/**"
      - "build.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain*"
      - ".cargo/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths: *code

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev
      - if: runner.os == 'Linux'
        run: cargo fmt --all -- --check
      - if: runner.os == 'Linux'
        run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo test --locked
